AWSTemplateFormatVersion: 2010-09-09
Description: Part 1 - Build a webapp stack with CloudFormation

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02396cdd13e9a1257 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
      KeyName: Datserver # <-- Change to use your key-pair name
      SecurityGroupIds:
        - !Ref Websg2
      UserData: 
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install httpd -y
            cd /var/www/html
            echo "Web Server 2 - North Virginiya" > index.html
            service httpd start
            chkconfig httpd on

  Websg2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ["-", [websg2, dev]]
      GroupDescription: "Allow HTTP/HTTPS and SSH inbound and outbound traffic"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0