AWSTemplateFormatVersion: 2010-09-09
Description: Part 1 - Build a webapp stack with CloudFormation

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06e46074ae430fba6 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
      KeyName: server1 # <-- Change to use your key-pair name
      SecurityGroupIds:
        - !Ref Websg

  Websg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ["-", [websg, dev]]
      GroupDescription: "Allow HTTP/HTTPS and SSH inbound and outbound traffic"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: abhi-tapadar-bucket-18042023
      Tags:
        - Key: CloudFormationLab
          Value: abhitapadar
