AWSTemplateFormatVersion: 2010-09-09
Description: Part 1 - Build a webapp stack with CloudFormation

Parameters:

  ImageId:
    Type: String
    Description: 'Windows AMI for NVirginia us-east-1 Region'
    Default: 'ami-070860697b2bcd4da'
  InstanceType:
    Type: String
    Description: Choosing  t2 micro because it is free
    Default: t2.micro
  KeyName:
    Description: RDP Keypair to login to the instance
    Type: String
    Default: DemoKey

Resources:
  WindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref Websg

  Websg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ["-", [websg]]
      GroupDescription: "Allow HTTP/HTTPS and RDP inbound and outbound traffic"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0
          
   #Allocate an Elastic IP in your Account
  DemoElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref WindowsInstance 
Outputs:
  WindowsInstance:
    Description: Instance Id 
    Value: !Ref WindowsInstance